const roster = [
  {
    id: '1',
    firstName: 'Justin',
    lastName: 'Fields',
    number: 1,
    position: 'QB',
    height: '6-3',
    weight: 228,
    age: 23,
    experience: 2,
    college: 'Ohio State',
  },
  {
    id: '2',
    firstName: 'Darnell',
    lastName: 'Mooney',
    number: 11,
    position: 'WR',
    height: '5-11',
    weight: 173,
    age: 25,
    experience: 3,
    college: 'Tulane',
  },
  {
    id: '3',
    firstName: 'Chase',
    lastName: 'Claypool',
    number: 10,
    position: 'WR',
    height: '6-4',
    weight: 238,
    age: 24,
    experience: 3,
    college: 'Notre Dame',
  },
  {
    id: '4',
    firstName: 'David',
    lastName: 'Montgomery',
    number: 32,
    position: 'RB',
    height: '5-11',
    weight: 224,
    age: 25,
    experience: 4,
    college: 'Iowa State',
  },
  {
    id: '5',
    firstName: 'Khari',
    lastName: 'Blasingame',
    number: 35,
    position: 'FB',
    height: '6-0',
    weight: 233,
    age: 26,
    experience: 4,
    college: 'Vanderbilt',
  },
  {
    id: '6',
    firstName: 'Cole',
    lastName: 'Kmet',
    number: 85,
    position: 'TE',
    height: '6-6',
    weight: 260,
    age: 23,
    experience: 3,
    college: 'Notre Dame',
  },
  {
    id: '7',
    firstName: 'Braxton',
    lastName: 'Jones',
    number: 70,
    position: 'LT',
    height: '6-5',
    weight: 310,
    age: 23,
    experience: 1,
    college: 'Southern Utah State',
  },
  {
    id: '8',
    firstName: 'Cody',
    lastName: 'Whitehair',
    number: 65,
    position: 'LG',
    height: '6-3',
    weight: 316,
    age: 30,
    experience: 7,
    college: 'Kansas State',
  },
  {
    id: '9',
    firstName: 'Lucas',
    lastName: 'Patrick',
    number: 62,
    position: 'C',
    height: '6-3',
    weight: 313,
    age: 29,
    experience: 6,
    college: 'Duke',
  },
  {
    id: '10',
    firstName: 'Teven',
    lastName: 'Jenkins',
    number: 76,
    position: 'RG',
    height: '6-6',
    weight: 321,
    age: 24,
    experience: 2,
    college: 'Oklahoma State',
  },
  {
    id: '11',
    firstName: 'Larry',
    lastName: 'Borom',
    number: 75,
    position: 'RT',
    height: '6-5',
    weight: 333,
    age: 23,
    experience: 2,
    college: 'Missouri',
  },
];

module.exports = { roster };
