const roster = [
  {
    id: '1',
    firstName: 'Justin',
    lastName: 'Fields',
    number: 1,
    position: 'QB',
    height: '6-3',
    weight: 228,
    age: 23,
    experience: 2,
    college: 'Ohio State',
  },
  {
    id: '2',
    firstName: 'Darnell',
    lastName: 'Mooney',
    number: 11,
    position: 'WR',
    height: '5-11',
    weight: 173,
    age: 25,
    experience: 3,
    college: 'Tulane',
  },
  {
    id: '3',
    firstName: 'Chase',
    lastName: 'Claypool',
    number: 10,
    position: 'WR',
    height: '6-4',
    weight: 238,
    age: 24,
    experience: 3,
    college: 'Notre Dame',
  },
  {
    id: '4',
    firstName: 'David',
    lastName: 'Montgomery',
    number: 32,
    position: 'RB',
    height: '5-11',
    weight: 224,
    age: 25,
    experience: 4,
    college: 'Iowa State',
  },
  {
    id: '5',
    firstName: 'Khari',
    lastName: 'Blasingame',
    number: 35,
    position: 'FB',
    height: '6-0',
    weight: 233,
    age: 26,
    experience: 4,
    college: 'Vanderbilt',
  },
  {
    id: '6',
    firstName: 'Cole',
    lastName: 'Kmet',
    number: 85,
    position: 'TE',
    height: '6-6',
    weight: 260,
    age: 23,
    experience: 3,
    college: 'Notre Dame',
  },
  {
    id: '7',
    firstName: 'Braxton',
    lastName: 'Jones',
    number: 70,
    position: 'LT',
    height: '6-5',
    weight: 310,
    age: 23,
    experience: 1,
    college: 'Southern Utah State',
  },
  {
    id: '8',
    firstName: 'Cody',
    lastName: 'Whitehair',
    number: 65,
    position: 'LG',
    height: '6-3',
    weight: 316,
    age: 30,
    experience: 7,
    college: 'Kansas State',
  },
  {
    id: '9',
    firstName: 'Lucas',
    lastName: 'Patrick',
    number: 62,
    position: 'C',
    height: '6-3',
    weight: 313,
    age: 29,
    experience: 6,
    college: 'Duke',
  },
  {
    id: '10',
    firstName: 'Teven',
    lastName: 'Jenkins',
    number: 76,
    position: 'RG',
    height: '6-6',
    weight: 321,
    age: 24,
    experience: 2,
    college: 'Oklahoma State',
  },
  {
    id: '11',
    firstName: 'Larry',
    lastName: 'Borom',
    number: 75,
    position: 'RT',
    height: '6-5',
    weight: 333,
    age: 23,
    experience: 2,
    college: 'Missouri',
  },
  {
    id: '12',
    firstName: 'Trevis',
    lastName: 'Gipson',
    number: 99,
    position: 'DL',
    height: '6-4',
    weight: 263,
    age: 25,
    experience: 3,
    college: 'Tulsa',
  },
  {
    id: '13',
    firstName: 'Justin',
    lastName: 'Jones',
    number: 93,
    position: 'DL',
    height: '6-3',
    weight: 309,
    age: 26,
    experience: 5,
    college: 'North Carolina State',
  },
  {
    id: '14',
    firstName: 'Angelo',
    lastName: 'Blackson',
    number: 90,
    position: 'DL',
    height: '6-4',
    weight: 315,
    age: 29,
    experience: 8,
    college: 'Auburn',
  },
  {
    id: '15',
    firstName: 'Al-Quadin',
    lastName: 'Muhammad',
    number: 55,
    position: 'DL',
    height: '6-3',
    weight: 250,
    age: 27,
    experience: 6,
    college: 'Miami',
  },
  {
    id: '16',
    firstName: 'Nicholas',
    lastName: 'Morrow',
    number: 53,
    position: 'LB',
    height: '6-0',
    weight: 216,
    age: 27,
    experience: 5,
    college: 'Greenville',
  },
  {
    id: '17',
    firstName: 'Jack',
    lastName: 'Sanborn',
    number: 57,
    position: 'LB',
    height: '6-2',
    weight: 234,
    age: 22,
    experience: 1,
    college: 'Wisconsin',
  },
  {
    id: '18',
    firstName: 'Joe',
    lastName: 'Thomas',
    number: 45,
    position: 'LB',
    height: '6-1',
    weight: 227,
    age: 31,
    experience: 8,
    college: 'South Carolina State',
  },
  {
    id: '19',
    firstName: 'Jaylon',
    lastName: 'Johnson',
    number: 33,
    position: 'CB',
    height: '6-0',
    weight: 196,
    age: 23,
    experience: 3,
    college: 'Utah',
  },
  {
    id: '20',
    firstName: 'Kyler',
    lastName: 'Gordon',
    number: 6,
    position: 'CB',
    height: '6-0',
    weight: 200,
    age: 22,
    experience: 1,
    college: 'Washington',
  },
  {
    id: '21',
    firstName: 'Eddie',
    lastName: 'Jackson',
    number: 4,
    position: 'S',
    height: '6-0',
    weight: 206,
    age: 28,
    experience: 6,
    college: 'Alabama',
  },
  {
    id: '22',
    firstName: 'Jaquan',
    lastName: 'Brisker',
    number: 9,
    position: 'S',
    height: '6-1',
    weight: 200,
    age: 23,
    experience: 1,
    college: 'Penn State',
  },
];

module.exports = { roster };
